surname = input("What is your surname? ")
firstname = input("What is your first name? ")
email = input("What is your email address? ")
phone = input("Please insert your phone number ")
job = input("what is your current job? ")
number = input("lastly, what is your id number? ")
print(surname.upper() , "," , firstname)
print(job)
print("ID" , number)
print(email)
print(phone)